#!/usr/bin/python

import os
import yaml

SECRETS_PATH = "/var/run/secrets/atomic-reactor"
SECRET_NAME = "kojisecret"
CONFIG_NAME = "osbs-box.yaml"

CONFIG_PATH = os.path.join(SECRETS_PATH, SECRET_NAME, CONFIG_NAME)

if os.path.exists(CONFIG_PATH):
   with open(CONFIG_PATH, "r") as f:
      data = yaml.load(f)

   hosts_data = data.get('hosts', None)
   if hosts_data:
      with open('/etc/hosts', 'a') as f:
         f.write('\n')
         for ip, hosts in hosts_data.items():
            f.write('{}\t{}\n'.format(ip, ' '.join(hosts)))
